[tool.poetry]
name = "datasets-preview-backend"
version = "0.1.0"
description = "API to extract rows of 🤗 datasets"
authors = ["Sylvain Lesage <severo@rednegra.net>"]

[tool.poetry.dependencies]
python = "^3.8"
datasets = "^1.10.2"
starlette = "^0.16.0"
uvicorn = "^0.14.0"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
watchdog = {extras = ["watchmedo"], version = "^2.1.3"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
