[tool.poetry]
name = "datasets-preview-backend"
version = "0.3.0"
description = "API to extract rows of 🤗 datasets"
authors = ["Sylvain Lesage <severo@rednegra.net>"]

[tool.poetry.dependencies]
python = "^3.8"
starlette = "^0.16.0"
uvicorn = "^0.14.0"
Pillow = "^8.3.1"
trec-car-tools = {path = "vendors/trec-car-tools/python3"}
apache-beam = "^2.31.0"
conllu = "^4.4"
kss = "^2.5.1"
lm-dataformat = "^0.0.19"
lxml = "^4.6.3"
nlp = "^0.4.0"
openpyxl = "^3.0.7"
py7zr = "^0.16.1"
tensorflow = "^2.5.0"
transformers = "^4.9.1"
wget = "^3.2"
kenlm = {url = "https://github.com/kpu/kenlm/archive/master.zip"}
nltk = "^3.6.2"
aiohttp = "^3.7.4"
datasets = {extras = ["streaming"], git = "https://github.com/huggingface/datasets.git", rev = "b9fb8b2567aecfb14ad0bc31b59329f573eb35df"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^21.7b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning"
]
